jwt:
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  token-validity-in-seconds: 2592000

twilio:
  TWILIO_ACCOUNT_SID: AC1f992454125cf5454177e5fe08e50b58
  TWILIO_AUTH_TOKEN: 8c727770c6d6b3e3cd4fba6088b471eb
  NUMBERPHONE_FROM: +19362516568
